videogular/videogular

- app/scripts/com/2fdevs/videogular/plugins/controls.js
- app/scripts/com/2fdevs/videogular/videogular.js
**BREAKING CHANGE**
Represent time (`currentTime`, `timeLeft`, `totalTime`) in milliseconds instead of Date objects. When I started using videogular I wondered why videogular uses `Date` objects for the representation of various times. Milliseconds are easier to calculate with and do not have the complexities of working with time zones. [jPlayer](https://github.com/happyworm/jPlayer), a major video player for jQuery, also does all its time-related calculations in seconds, and I see no reason why videogular should not do the same.
In the videogular-controls plugin, the `currentTime`, `timeLeft` and `totalTime` variables are exposed to the UI. For this, the AngularJS [date filter](https://docs.angularjs.org/api/ng/filter/date) is used. This remains unchanged after this PR, since the …
> Represent time (currentTime, timeLeft, totalTime) in milliseconds instead of Date objects.

- README.md
For those who are migrating from earlier `<1.x` versions, this can provide some relief from obscure console errors. What do you guys think?
> Add breaking naming changes to docs

- app/scripts/com/2fdevs/videogular/directives/vg-media.js
Hello Videogular!
I had difficulties when trying to use the Videogular API callback: `vgChangeSource()`. 
[The API ](http://www.videogular.com/tutorials/videogular-api/) lists this callback as ```vgChangeSource($source): Called when __volume__ has been changed. Returns the new media source.```
And [the docs](http://www.videogular.com/docs/#/api/com.2fdevs.videogular.directive:videogular) list the callback as: ```Function name in controller's scope to change current video source. Receives a param with the new video.```
With this edit, my wrapper directive controller can now bind to `vgChangeSource` and be notified whenever the video element begins playing a new source. 
Use case
* server has a video file stored at several resolutions and bitrate qualities
* users must be able to select a …
> vgChangeSource callback triggers when the video player begins a new file

- app/scripts/com/2fdevs/videogular/constants/vg-constants.js
- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
- app/scripts/com/2fdevs/videogular/directives/videogular.js
- app/scripts/com/2fdevs/videogular/plugins/vg-controls/vg-volume/vg-mute-button.js
- app/scripts/com/2fdevs/videogular/plugins/vg-controls/vg-volume/vg-volume-bar.js
- app/scripts/com/2fdevs/videogular/services/vg-utils.js
- test/spec/plugins/vg-controls.js
This PR is the result of a series of emails with Elecash discussing my application's needs, but the changes are intended for flexibility and customization for developers.
New features:
* Volume changes are saved to localStorage under the key 'videogularVolume'
* media volume is set from localStorage's value on initialization (if available) otherwise defaults to 100% as it always has.
* vgMuteButton and vgVolumeBar will load with the correct values if volume is not 100%.
* new callback: vgCanPlay($event). Forwards the media elements 'canplay' events to the developer. Videogular was already internally using this event. Now, the event is also bindable for external use.
After feedback from @Elecash, I changed sessionStorage to localStorage. This allows the volume setting to persist after …
> New features: Persistent volume and vgCanPlay callback

- app/scripts/com/2fdevs/videogular/services/vg-utils.js
Hello, Videogular doesn't work on Firefox Developer Edition (39.0a2 currently).
I've done a quick fix for that. Maybe you have a more beautiful fix to replace this one, but the idea is here.
Regards & and thanks for the job,
Nainterceptor
> Quick fix for Firefox 39 (Dev edition) which have offset

- app/scripts/com/2fdevs/videogular/plugins/vg-controls/vg-play-pause-button/vg-play-pause-button.js
- app/scripts/com/2fdevs/videogular/plugins/vg-overlay-play/vg-overlay-play.js
This closes #40 .
always set player state rather than when the newVal != oldVal
Test results are the same as before making changes:
```
Firefox 35.0.0 (Mac OS X 10.10): Executed 53 of 55 (skipped 2) SUCCESS (2.853 secs / 3.347 secs)
```
```
Chrome 42.0.2311 (Mac OS X 10.10.3) LOG: 'Failed loading manifest: source.mpd, retry in 500ms attempts: 3'
Chrome 42.0.2311 (Mac OS X 10.10.3) LOG: 'Failed loading manifest: source.mpd, retry in 500ms attempts: 3'
Chrome 42.0.2311 (Mac OS X 10.10.3): Executed 53 of 55 (skipped 2) SUCCESS (4.114 secs / 4.013 secs)
TOTAL: 106 SUCCESS
```
> This ensures that the controls playPauseButton and overlay play are in play state when vg-auto-play is true

- app/scripts/com/2fdevs/videogular/services/vg-utils.js
Safari private browsing mode disables local storage, which causes an error to be thrown when the setVolume method is called. This change amends the supportsLocalStorage utility method to return false when local storage is available but disabled, such as in the case of Safari private browsing.
Issue: https://github.com/2fdevs/videogular/issues/237
> Fixes error caused by Safari private browsing mode

- app/scripts/com/2fdevs/videogular/directives/vg-media.js
Watch both vgSrc and API
Regression on 1.2.4 scope.vgSrc doesn't support to be defined after videogular, the if statement is executed only once
> fix regression on 1.2.4 - scope.vgSrc can't be defined after videogular

- app/scripts/com/2fdevs/videogular/plugins/vg-controls/vg-scrub-bar/vg-scrub-bar.js
Seek was broken on Android as this 2fdevs/videogular#287 points out.
It turns out the [UIEvent.layerX](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/layerX) variable was being used to calculate the seek time but it is not part of the standard and it is broken on Android. 
I removed the layerX dependency using [this](http://stackoverflow.com/questions/10132758/cross-browser-solution-for-replacing-the-use-of-event-layerx-and-event-layery) piece of advice and now seek works on Android.
I tested this on Android 5.1.1 (Xperia Z3) and iOS 9.0.2 (iPad Mini 2).
> Fixed seek on android

- app/scripts/com/2fdevs/videogular/services/vg-utils.js
Hi,
I had problems with Videogular recognising a WP8.1 phone with IE11 as an iOS device. It of course, tried to use 'webkitEnterFullscreen' function and crashed.
I updated the userAgent checking for a bit more precise check.
Also you should consider using a reliable UA parser (I recommend *ua-parser-js* bower package) as a dependency for this purpose. They are usually a bit heavy for a single check, so it's something the Videogular team should consider.
I hope you can also test this PR, it works for me and this specific WP and it still works on all available iOS devices I have access to.
> more precise iOS device detection

- app/scripts/com/2fdevs/videogular/directives/vg-media.js
- app/scripts/com/2fdevs/videogular/services/vg-utils.js
Cordova/phonegap allows autoplay by default. In particular calling
play() directly always works.
> Autoplay enabled for mobile devices on cordova

- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
When using hot keys to seek, the percent value can fall outside the valid range and cause visual defect when playhead seeks outside of progress bar bounds.
> Normalized value for seek by percent so it can't fall out of valid range

- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
If the start time for a virtual clip was set to 0, the playback would not stop after the clip duration. Added an extra condition for catching if startTime === 0
> Clip start time

- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
Prevents errors from being thrown upon calling clearMedia() when mediaElement doesn't exist. This can be the case when some form of deferred loading of vg-media has been implemented where mediaElement might not always be initialised.
> Defensive check for mediaElement in clearMedia method

- app/scripts/com/2fdevs/videogular/services/vg-utils.js
- test/spec/services/vg-utls.js
Solve this problem: When "Block third-party cookies and site data" on chrome://settings/content is enabled and videogular embeded as iframe than the player throws "Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document."
> Put the obtaining a sessionStorage under the try-catch block

- app/scripts/com/2fdevs/videogular/plugins/vg-poster/vg-poster.js
- test/spec/plugins/vg-poster.js
because the poster img (image) is for presentation purposes and this change solves an accessibility issue where accessibility auditors require all img tags to have either an "alt" attribute or role="presentation".
> poster plugin img role presentation for accessibility

- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
- app/scripts/com/2fdevs/videogular/directives/vg-media.js
Enable the possibility to provide a single URL string as source for the video player. This can be very convenient in some cases.
> Source can be a simple URL string

- app/scripts/com/2fdevs/videogular/directives/vg-media.js
- test/spec/directives/videogular.js
- You may now supply **vgNativePlayBlacklist** on **vgMedia** to prevent native playback of sources as
desired. It expects an array of functions accepting  the media source and user agent. If any of
these return true,  native playback will not be attempted. This  may be useful in combination with
playback plugins. For example, you may want to use hls.js  in Android Chrome rather than its native
handling.
- Some clean up of **changeSource()** while I was in there. I found that it wasn't consistent across the various sources cases. The post-apply behavior has also been refined to run only when you've actually applied a source or fire an error if it couldn't. Should be easier to follow.
> Native play blacklist

- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
> Fix for wrong firing of `cuePoint.onComplete` when cuePoints list changed

- app/scripts/com/2fdevs/videogular/controllers/vg-controller.js
- test/spec/directives/videogular.js
1. Add input validation to seekTime() to ensure that it only accepts finite numbers.
1. Safer handling of play() and pause() to silence some console noise. Some browsers have async methods and will complain when you interrupt an operation.
1. New _API.activeSource_ to provide convenient access to the applied source. There's presently an event to expose this to the outside, but no convenient way to get to it internally.
1. Fix to the doc comments about expected source input. String not supported.
1. Add support for a new optional _isLive_ flag on the source input object. This allows you to override the built in detection logic, which may not be reliable in all cases such as with playback plugins.
> Small fixes + enhancements round 1

- app/scripts/com/2fdevs/videogular/plugins/vg-controls/vg-playback-button/vg-playback-button.js
docs(vgPlaybackButton): Correct a typo in the inline doc for vgPlaybackButton where it is mistakenly
Fixes #422.
> Correct ngPlaybackButton name in its comments
